services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: handitalents
    ports:
      - "5433:5432"
    volumes:
      - microservices_pgdata:/var/lib/postgresql/data

  core-service:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      PORT: 5000
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/handitalents
      JWT_SECRET: votre_secret_jwt
      JWT_EXPIRES_IN: 1d
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./handi_talents-main_abir:/app
    depends_on:
      - postgres

  auth-service:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run db:migrate && npm run dev"
    environment:
      PORT: 4101
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/handitalents
      JWT_SECRET: votre_secret_jwt
      JWT_EXPIRES_IN: 1d
    ports:
      - "4101:4101"
    volumes:
      - ./microservices/auth-service:/app
    depends_on:
      - postgres

  user-service:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run db:migrate && npm run dev"
    environment:
      PORT: 4102
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/handitalents
      JWT_SECRET: votre_secret_jwt
      JWT_EXPIRES_IN: 1d
    ports:
      - "4102:4102"
    volumes:
      - ./microservices/user-service:/app
    depends_on:
      - postgres

  job-service:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run db:migrate && npm run dev"
    environment:
      PORT: 4103
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/handitalents
      JWT_SECRET: votre_secret_jwt
      JWT_EXPIRES_IN: 1d
    ports:
      - "4103:4103"
    volumes:
      - ./microservices/job-service:/app
    depends_on:
      - postgres

  api-gateway:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      PORT: 4000
      FRONTEND_URL: http://localhost:3000
      AUTH_SERVICE_ENABLED: "true"
      AUTH_SERVICE_URL: http://auth-service:4101
      USER_SERVICE_ENABLED: "true"
      USER_SERVICE_URL: http://user-service:4102
      JOB_SERVICE_ENABLED: "true"
      JOB_SERVICE_URL: http://job-service:4103
      CORE_SERVICE_URL: http://core-service:5000
    ports:
      - "4000:4000"
    volumes:
      - ./microservices/api-gateway:/app
    depends_on:
      - core-service
      - auth-service
      - user-service
      - job-service

volumes:
  microservices_pgdata:
