export const TUNISIAN_GOVERNORATES = {
  Ariana: ["Ariana Ville", "Cite Ettadhamen", "Kalaat El Andalous", "La Soukra", "Mnihla", "Raoued", "Sidi Thabet"],
  Beja: ["Amdoun", "Beja Nord", "Beja Sud", "Goubellat", "Medjez El Bab", "Nefza", "Teboursouk", "Testour", "Thibar"],
  "Ben Arous": [
    "Ben Arous",
    "Bou Mhel El Bassatine",
    "El Mourouj",
    "Ezzahra",
    "Fouchana",
    "Hammam Chott",
    "Hammam Lif",
    "Medina Jedida",
    "Megrine",
    "Mohamedia",
    "Mornag",
    "Rades",
  ],
  Bizerte: [
    "Bizerte Nord",
    "Bizerte Sud",
    "El Alia",
    "Ghar El Melh",
    "Ghezala",
    "Joumine",
    "Mateur",
    "Menzel Bourguiba",
    "Menzel Jemil",
    "Ras Jebel",
    "Sejnane",
    "Tinja",
    "Utique",
    "Zarzouna",
  ],
  Gabes: [
    "Dkhilet Toujane",
    "El Hamma",
    "Gabes Medina",
    "Gabes Ouest",
    "Gabes Sud",
    "Ghannouch",
    "Habib Thameur Bouatouch",
    "Mareth",
    "Matmata",
    "Menzel El Habib",
    "Metouia",
    "Nouvelle Matmata",
    "Oudhref",
  ],
  Gafsa: [
    "Belkhir",
    "El Guettar",
    "El Ksar",
    "Gafsa Nord",
    "Gafsa Sud",
    "Mdhila",
    "Metlaoui",
    "Moulares",
    "Redeyef",
    "Sened",
    "Sidi Aich",
    "Sidi Boubaker",
    "Zannouch",
  ],
  Jendouba: ["Ain Draham", "Balta - Bou Aouane", "Bou Salem", "Fernana", "Ghardimaou", "Jendouba", "Jendouba Nord", "Oued Meliz", "Tabarka"],
  Kairouan: [
    "Ain Djeloula",
    "Bou Hajla",
    "Chebika",
    "Echrarda",
    "El Alaa",
    "Haffouz",
    "Hajeb El Ayoun",
    "Kairouan Nord",
    "Kairouan Sud",
    "Menzel Mehiri",
    "Nasrallah",
    "Oueslatia",
    "Sbikha",
  ],
  Kasserine: [
    "El Ayoun",
    "Ezzouhour",
    "Feriana",
    "Foussana",
    "Haidra",
    "Hassi El Ferid",
    "Jedelienne",
    "Kasserine Nord",
    "Kasserine Sud",
    "Majel Bel Abbes",
    "Sbeitla",
    "Sbiba",
    "Thala",
  ],
  Kebili: ["Douz Nord", "Douz Sud", "Faouar", "Kebili Nord", "Kebili Sud", "Rjim Maatoug", "Souk Lahad"],
  Kef: ["Dahmani", "El Ksour", "Jerissa", "Kalaat Khasba", "Kalaat Senan", "Kef Est", "Kef Ouest", "Nebeur", "Sakiet Sidi Youssef", "Sers", "Tajerouine", "Touiref"],
  Mahdia: [
    "Bou Merdes",
    "Chebba",
    "Chorbane",
    "El Bradaa",
    "El Jem",
    "Essouassi",
    "Hebira",
    "Ksour Essef",
    "Mahdia",
    "Mellouleche",
    "Ouled Chamekh",
    "Rejiche",
    "Sidi Alouane",
  ],
  Manouba: ["Borj El Amri", "Djedeida", "Douar Hicher", "El Batan", "Manouba", "Mornaguia", "Oued Ellil", "Tebourba"],
  Medenine: ["Ben Gardane", "Beni Khedache", "Djerba Ajim", "Djerba Houmt Souk", "Djerba Midoun", "Medenine Nord", "Medenine Sud", "Sidi Makhlouf", "Zarzis"],
  Monastir: [
    "Bekalta",
    "Bembla",
    "Beni Hassen",
    "Jemmal",
    "Ksar Hellal",
    "Ksibet El Mediouni",
    "Moknine",
    "Monastir",
    "Ouerdanine",
    "Sahline",
    "Sayada - Lamta - Bouhjar",
    "Teboulba",
    "Zeramdine",
  ],
  Nabeul: [
    "Beni Khalled",
    "Beni Khiar",
    "Bou Argoub",
    "Dar Chaabane El Fehri",
    "El Haouaria",
    "El Mida",
    "Grombalia",
    "Hammamet",
    "Hammam Ghezaze",
    "Kelibia",
    "Korba",
    "Menzel Bouzelfa",
    "Menzel Temime",
    "Nabeul",
    "Soliman",
    "Takelsa",
  ],
  Sfax: [
    "Agareb",
    "Bir Ali Ben Khalifa",
    "El Amra",
    "El Hencha",
    "Graiba",
    "Jebiniana",
    "Kerkennah",
    "Mahres",
    "Menzel Chaker",
    "Sakiet Eddair",
    "Sakiet Ezzit",
    "Sfax Ouest",
    "Sfax Sud",
    "Sfax Ville",
    "Skhira",
    "Thyna",
  ],
  "Sidi Bouzid": [
    "Bir El Hafey",
    "Cebbala Ouled Asker",
    "El Hichria",
    "Essaida",
    "Jilma",
    "Meknassy",
    "Menzel Bouzaiane",
    "Mezzouna",
    "Ouled Haffouz",
    "Regueb",
    "Sidi Ali Ben Aoun",
    "Sidi Bouzid Est",
    "Sidi Bouzid Ouest",
    "Souk Jedid",
  ],
  Siliana: ["Bargou", "Bou Arada", "El Aroussa", "El Krib", "Gaafour", "Kesra", "Makthar", "Rouhia", "Sidi Bou Rouis", "Siliana Nord", "Siliana Sud"],
  Sousse: [
    "Akouda",
    "Bouficha",
    "Enfida",
    "Hammam Sousse",
    "Hergla",
    "Kalaa Kebira",
    "Kalaa Seghira",
    "Kondar",
    "Msaken",
    "Sidi Bou Ali",
    "Sidi El Hani",
    "Sousse Jawhara",
    "Sousse Medina",
    "Sousse Riadh",
    "Sousse Sidi Abdelhamid",
    "Zaouiet - Ksibet Thrayet",
  ],
  Tataouine: ["Beni Mehira", "Bir Lahmar", "Dehiba", "Ghomrassen", "Remada", "Smar", "Tataouine Nord", "Tataouine Sud"],
  Tozeur: ["Degache", "El Hamma du Jerid", "Hazoua", "Nefta", "Tamerza", "Tozeur"],
  Tunis: [
    "Bab El Bhar",
    "Bab Souika",
    "Carthage",
    "Cite El Khadra",
    "Djebel Jelloud",
    "El Hrairia",
    "El Kabaria",
    "El Menzah",
    "El Omrane",
    "El Omrane Superieur",
    "El Ouardia",
    "Ettahrir",
    "Ezzouhour",
    "La Goulette",
    "La Marsa",
    "Le Bardo",
    "Le Kram",
    "Medina",
    "Sejoumi",
    "Sidi El Bechir",
    "Sidi Hassine",
  ],
  Zaghouan: ["Bir Mcherga", "El Fahs", "Nadhour", "Saouaf", "Zaghouan", "Zriba"],
} as const;

export type TunisianGovernorate = keyof typeof TUNISIAN_GOVERNORATES;

export const TUNISIAN_GOVERNORATE_OPTIONS = Object.keys(TUNISIAN_GOVERNORATES) as TunisianGovernorate[];
